---
title: 放下幻想 努力创造
author: 小冠
date: '2019-05-03'
slug: humancreative
categories:
  - 我思故我在
tags:
  - 创造
banner: banners/creative.png
description: '大自然虽无奇不有，特定功能的东西，仍需人的创造'
images: []
menu: ''
---

<!--more-->
当结果很容易检验，人们不会心存幻念，谁的钻石掉了，不会想着去外面马路上、沙滩上再捡一颗回来。
吕然世间无奇不有，谁也不能保证，奇秒的大自然就会磨砺出一颗小石子，刚好镶在自己的戒托上呢？
不偏不倚、不多不少。 **自然所造之石恐怕是“恒河沙数”也不够数的，自然之奇秒是不假，
但这种玄秒之事刚好发生在自己身上的概率又有多少？** 所以，钻石掉了人的不会去沙滩上找，
还是痛快的去珠宝店吧。

任何具有特定功能的东西，无一不依靠人的创造，当然是在大自然给了我们数不清的原材料的基础上，
但与其在这海量的原材料上“淘金”，远不如自己动手创造来得划算。**功能越是特别，就越是要靠人的创造，**
实际上远不需要钻石那么特别，一把锋利的石斧，就足以断了去捡的念想，如果只是简单砸一下，
去踫踫运气还是不错的选项。

道理本来简单，捡石头是如此直观，人们平常生活中遇到恐怕也不会想这么多。
但放到吃上来，原来简单的道理却不见了，想着踫运气的人成倍的增加，
原因怕是人的身体复杂，**相关因素太多，结果与原因之间没有石头那么立杆见影了。**

人想去找个吃的，不被毒死，大概率还是很容易实现的，相当于找个砸东西的石头；
不仅能活着，还想吃饱，也不算难，人类在漫长的进化中已经积累了足够多的知识来完成这个任务，
难度类比造石斧吧；不满足于吃饱还想吃好，这个可就难了，人人都说纯天然好，可真在身边找找，
**我们的日常饮食无一不是经过人工，甚至是数代，乃至成千上万年的努力，不断培育、筛选的结果。**
我们平常所吃到小麦、水稻，鸡，猪，蔬菜、水果、肉类，能达到现在的口感和产量，
都不是一代人就能完成的，包含了不断积累的创造，这个难度类似于造钢斧吧。
红尖一骑妃子笑，无人知是荔枝来，怕是那诗流传下来了，其实那会的荔枝远没有现在的好吃，
产量也只能满足于王公贵族吧。

吃好，只是让身体上某些细胞感受到良好的刺激，在营养上满足人的需要，
在产量上满足更多的需求，细想起来也算不上特别到不得了的地步，已经需要如此之多的人为创造了。
如果再特别一点呢，只吃下少许，就能达到杀灭人体内的致病物，扭转人体发育的方向，
等非常细微且特别的功能，又到如何？我们还能把希望寄托在“大浪淘沙”的寻找上吗？
**想从大自然中寻找任何天然动植物，吃下去达到上述特定目标，
其成功的概率甚至要比去海滩上找石子镶在自己戒托上的还要小得多。**
世间之理本就如此残酷，放下幻想，努力创造！
