---
title: 机会均等——论最大熵模型在机关人力资源管理中的应用
author: Guan
date: '2019-07-12'
slug: 2019-07-govhr
categories:
  - 我思故我在
tags:
  - 管理
  - 人事
banner: '/banners/govhr.JPG'
description: '机关提高工作效能，为何必须机会均等、广泛轮岗，基于最大熵模型的分析'
images: []
menu: ''
---

<!--more-->

> 摘要：最大熵原理是信息论的基本原理之一，简单说就是要保持各种可能选项的概率均等，以使信息熵达到最大，
用在人力资源管理上就是选人用人要公平，机会均等。本文从理想官僚制模型、理性人假设和熵增原理等作为机关的现实约束条件，
应用最大熵模型原理，阐述了在机关提高工作效能，就必须机会均等、广泛轮岗。

## 1.理想官僚制模型——好结果要有好制度保证
德国的社会学家马克思`韦伯提出过**理想的官僚制模型，包括5个原则:等级化、专业化、流程化、文书化和非人格化**，
每一点都在强调官僚队伍的集中统一性。我们都知道做好工作，优秀的人格特质也是必不可少的，但为何韦伯要说非人格化呢？
其实这也很好理解，官僚队伍是庞大的、复杂的、流动的，我们不能把持续稳定的工作输出寄托在个人的优秀品质上，
当然这并不是说不要优秀的品质，而是说，**要求个人优秀，就必须落实在制度层面，使得官僚保持优秀，而不仅仅要求个人自我保持优秀**。

我们的公务员统一招考就是很好的例子，要求硕士毕业，基层工作经验2年，按职务报考，符合相应的主修专业要求，三比一入围面试等等，
有了这一套制度保证，筛选出来的人在文化、表达、沟通、基本技能等多方面处于全社会人群中相当优秀的位次，据我判断应在前1%的水平。

## 2.理性人假设——优秀平庸是博弈的结果
但这些人到了实际工作中，是否真能做到相当优秀的工作效能呢？恐怕未必，这就要提出另一个前提——
**理性人假设:人会根据现实处境和自身条件选择最优的博弈策略，以使自己的预期收益最大化，或说预期损失最小化**。

也就是说，当初的天之骄子进入公务员队伍后，会根据机关实际情况和自身条件选择自己的博弈策略，
以使自己的预期收益最大化，或预期损失最小化，那么最大化自己的利益时，是否同时能达到工作效能的最大化呢？
就通常情况而言是显然是未必如是的。有调查研究，人力资源的表现的时间相关性最多持续3年，
也就是说，**现在的工作表现是否优秀，3年前已经完全没关系了**。
如此，为何当初考进机关的是百里挑一的优秀人才，却渐渐变得普通甚至平庸呢，又如何使他们持续保持优秀呢？

## 3.熵增原理——封闭系统总是越来越糟糕
热力学有一条第二定律，也叫熵增原理，说的是在封闭系统总是向熵增的方向发展，在管理中使用的也很多，
管理学的通俗的表述是:**封闭系统总是越来越糟糕**，这是个残酷的原理，那如何对抗熵增呢？
自然是反其道行之，打破封闭，**让系统与外面流通起来，或从引入外部力量输入负熵实现有效管理**。

不少组织使用这条来实现人力资源的有效组织，提高效能，如谷歌，高标准招聘员工的同时，高标准的工作也让差评员工离职。
更典型是军队，如美军，每年从大学招入军官，同时也有军官退役，上尉及以上每年都要有一定比例退役，
选择退役的标准就是两次晋升失败，有进有出的同时，保证出的是在本系统不够优秀的（退役后在军外可能很优秀），
整个军官队伍就能保持高水准，也就是说军官的工作水平可能的状态数很少，熵较低，且不增。

这对机关来说是个挑战，机关的人员进口有公务员招考和军转，优秀还可以保证，
但出口却只有退休，不像军队每个层级都有一定的淘汰比例，大部分机关极少有晋升或调到外部门的，更极少有离职，
哪怕有也是个案，并非制度性的，**与外部交流程序太低，可以近似看成封闭系统，定会向熵增的方向发展**。

## 4.机会均等——最大熵模型
这就可以回答为何当年百里挑一老进来的优秀公务员，慢慢变得平庸不堪呢，一方面是人自身和外部条件共同作用下自然发展的结果；
另一方面，机关是个近似封闭的系统，无法像军队和公司一样淘汰表现不好人，长期积累工作水平各种状态的人都会存在。
因此**机关人员工作水平从优秀到糟糕各种都有，状态数很多，也就是说熵很大**。

工作表现糟糕的人，能不能通过培训或激励成为优秀呢？从单个个体来说当然是可能的，但对整个系统而言各种状态会始终存在。
**机关不但没有足够的淘汰制度，连激励制度其实也很少**，机关的分配基本上按等级进行，
不但工资，其他福利，大如分房，小如孩子上幼儿园、办公室环境也都完全和等级挂钩。
也就是说，**人的博弈策略只能面向等级晋升设计，如果晋升的博弈策略成功概率很低，显然选择消极怠工就成了最优博弈策略**，
因为不被淘汰出局的前提下，收益如不能增加，那么付出越少损失就越少，符合理性人假设。

如何使工作表现不好的人转变，从而达到工作效能上的最大化呢？根据理想官僚制度和理性人假设，
就必须**设计一套制度，改变人的外部条件——即机关环境，**
**使得每个人预期收益最大化或损失最小化的同时，尽可能达到工作效能上的最大化的结果。**
根据熵增原理，就只有引入外部力量强化管理输入负熵实现有效管理，
这是可以实现的，哪怕机关的人的不流动的，但机关有上级、有法律、有制度，这同样是外部力量，
如果能用好这样的外部力量，同样可以实现有效管理，对抗熵增。

那么，**什么样的外部条件会让人不会倾向于选择消极怠工的博弈策略呢？就是让人无法预测晋升可能性**，
**从机关角度看，就是使所有人（或所有同等条件的人）具有均等的晋升概率**，
**个人无从预测自己是否比别人更容易或更不容易晋升，努力工作就成为比消极怠工更优的博弈策略**。

这就是最大熵模型，不过这里的熵不是第3点说的的热力学的熵，而是信息熵，其原理是：
**对于未发生的事，不做任何主观假设，保持各种可能性均等的概率，此时信息熵达到最大**，
**用在人力资源管理上，就是保持晋升机会均等，此时关于晋升的信息熵最大，**
**参与博弈的人无法对自己晋升的可能性做出偏向性预测**，
消极怠工的博弈策略就不是可预期收益最大化的策略，从而倾向于选择努力工作。


## 5.如何应用
晋升时，各种不同类别的人，应该保持应有的比例，如年龄、院校、专业等等。
但实际上晋升又应该以优秀的工作表现为标准，这两者如果协调呢？
优秀的标准是什么？一个显然的标准是在重要的岗位上或重要的工作中表现优秀，
如果这样简单的晋升，显然会造成重要的处室不停的晋升，而有的处室则没有机会晋升，
就没有保持均等概率，违背了最大熵模型的原理。
按照最大熵模型和机会均等的做法应该是**保持广泛合理的轮岗，重要的处室和边缘处室的人能相互轮岗，**
**不同专业能相互轮岗，哪怕有的人因其自身原因不堪大用，也要保持轮岗，**
**这样在晋升时依然可以按优秀标准选人用人，也同时能符合最大熵模型的原理**，
不但使自身条件优秀的人经受了更多磨练，更多人也经受了考验提高了能力，
同时在晋升上尽可能保持了机会均等，提高了人的工作积极性。



