---
title: 空前的成功需要崭新的物种
author: 小冠
date: '2020-12-20'
slug: ReadHowGoogleWorks
categories:
  - 我思故我在
tags:
  - 管理
  - 读书
banner: '/banners/hgw.jpg'
description: '想获得空前的成功，必须打造或变成一个新的物种，读谷歌前CEO施密特介绍谷歌管理方法《重新定义公司》有感'
images: []
menu: ''
---

<!--more-->
读书笔记：空前的成功需要崭新的物种

# 导读
最近读了谷歌前CEO施密特介绍谷歌的书，结合正在思考的一些问题写了篇读书笔记。分享出来。

我认为，成功是一种筛选机制的结果，谷歌是一家非常成功的互联网公司，回到谷歌初创时，同类业务的公司不止谷歌一家，十几年下来，大都死的死并得并，只有谷歌生存发展壮大了，成为了市值近万亿的公司，除了运气成份，一定有其合理性，因此我们在研究并借鉴谷歌的经验。这是一本很有意思的书。

成功，一定要有其内部的独特性来支撑，正所谓是水到渠成，内部的经营管理就是修渠的过程。这个道理应该有助于理解，大清国即使不被列强欺负也一定不能发展壮大，国企也一定不能发展成为世界一流的公司，因为其内部结构、运行模式不支撑其达到上述目的。为什么有人会有这样的想法呢，因为他们看不到内部一些特点将来会导致的结果，而一些企业家，哪怕并没有研究过谷歌，但一样能让自己的企业发展壮大，因为他们能认识到一种模式能导致什么样的结果。


# 第1则   奢华的公摊 拥挤的办公室
> 很多人都熟悉谷歌员工享有的五花八门的娱乐设施：排球场、保龄球场、攀岩壁、幻灯片放映室、带有私人教练的健身房、小型游泳池、供人在办公楼间代步的彩色自行车、免费的高档餐厅，以及配有各式小食、饮品和顶尖意式咖啡机的厨房。但同时，谷歌的办公室却非常拥挤，一排排物品堆积、混乱不堪的隔间。

谷歌的大人物如何呢？

> 当CEO施密特来到办公室时，却发现里面竟然已经进驻了几位软件工程师，他没有把这些工程师从办公室里请出去，而是自己搬到了隔壁一间带一个窗户的房间——这里更像储藏间，而不像办公室。一天早晨，埃里克通过走廊走进储藏间，不，应该是他的办公室，他的办公室又有了一位新室友，是一位搜索工程师，因为他自己的办公室已经有5个人了，就搬到了CEO施密特的办公室。

虽然办公室拥挤，但谷歌慷慨向员工提供工作用到的各种资源，谷歌早期，液晶显示器还非常昂贵，谷歌就为每位员工购买了液晶显示器，并且由高管亲手的交到员工手里。

一个简单的安排，却体现谷歌的管理哲学：办公室是用来工作的，不是用来展现等级的。与政府机关不同，也与传统企业也不同，这些地方的办公室在制造阻隔、强调地位。而在谷歌，办公室设计是本着激发活力、鼓励交流的理念。谷歌将办公室弄得拥挤不堪，以降低等级攀比，同时也促进员工之间的交流，进而促进创新，建设奢华的公共空间也是如此，让员工们休息在一起，玩在一起，促进相互交流。

# 第2则  人才的进退去留
谷歌的招聘理念很简单，就是要一流的，但在淘汰人方面也很谨慎，因为会影响士气，其次如果到了要淘汰10%的程度，就会认为是招聘出了问题，招太多不合适的人，或者内部管理出了问题，把人才都搞成了庸才。招一流人才不仅仅是完成眼下的工作，而是为长远打算，如果新来的水平总低于现有人力的平均水平，随着企业的发展壮大，人才队伍会越来越差，离失败就不远了。

如何能保证找到一流的人才，谷歌也形成一了一系列自己的办法，有一点特别值得主意，创始人佩奇、布林，以及高官也会参与到招聘工作，甚至不局限于高级职位，相当长的时间，他们用在面试应聘者的时间甚至占了40%。而作出决定，是通过一个委员会，而且要一致同意。

这是佩奇和布林从美国大学学来的，美国大学一般不开除教授，因此在招聘和选拔时就非常谨慎。在谷歌，招聘不是人事部门说了算，也不是用人部门说了算，而是避开层级，用委员会。这一点很值得深思，在缺乏淘汰机制下如何能用好人是个很用的问题，我认为企业的整体发展激励、内部的文化氛围和外部竞争很重要，没有这几条作为根本约束力，人总是有惰性的。

另外，谷歌也推行内部岗位交流，因为虽然谷歌不怎么淘汰人，但是人才会跳槽，谷歌的办法就是让他们轮岗，不断有新的挑战，甚至在没有合适岗位时不惜为他们量身定制。谷歌也意识到一个问题，轮岗本心是好，但是人的本能是倾向于把最好的员工留给自己用，把差得轮出去，如此则违背轮岗的初衷，但书中并没有给出解决这个问题的答案。

# 第3则  领导与层级
扁平层级是很多人都会叫在嘴上的，谷歌是很坚持这一点，有时甚至坚持过了头，有段时间甚至取消了整个中层，后来证明这也是不可取的，导致直接向高层汇报的人太多，让高层过载。不过谷歌仍然坚持，一位管理职直接管理的下级不能少于7位，一般都在15-20位。

与层级息息相关的是领导的角色定位，谷歌的领导，也不是高高在上的人，不但工作，生活和娱乐也经常是在谷歌，不难想象，如果顶层领导高高在上，中层领导很快会照章学样，公司一定会成为个等级森严的地方，失去活力。谷歌上市前，佩奇和布林每次都会在公司和员工一起打旱冰球，一次，一个中国考察团正在合影，CEO施密特招呼远处一位刚打完球的年轻人过来合影，那人走了过来，站在人群中间，这人就是布林。这也是谷歌内部层级不明显上下贯通的体现。

虽然三驾马车有着崇高的人望，但绝不是说一不二、一言九鼎，事实上谷歌内部根本没有这样的人，因为他们的领导方式不是这样，领导者的定位也不是这样。叛逆和不盲从权威是硅谷的基因，谷歌甚至更胜一筹，在谷歌有句名言——别听领导的。谷歌员工有相当的自主权，有人甚至违抗上级命令做出过一些项目。谷歌鼓励员工有20%的自主时间，有不少项目都是工程师们用这些时间捣鼓出来的，我认为这一点也非常重要，虽然花了重金，但一定不能用尽员工百分之百的力，要留给员工仰望星空的时间，用于学习、反思甚至是天马行空，这样才能让他们不断提高，长远看对公司是有利的，谷歌的20%找到门道了。

谷歌还有其独特的周五下午吐槽时间，名为“谢天谢地又到周五”，由佩奇和布林主持，员工们往往会抛出尖锐的问题，有还没适应谷歌文化的新员工甚至怀疑问问题的人会不会被开除。多年来，吐槽大会中，佩奇和布林会请新员工亮相，为他们作介绍，也会宣布公司的重大事项，甚至在其他公司看来是绝密的内容，如公司的账务报表。谷歌上市前的最后一个吐槽大会上，CEO施密特最后一次宣布了公司的财务状况，因为法律规定，上市公司是不能这样做的。

总之，谷歌内部的非常鼓励分享的，而且最高层以身作责，任何好的东西，如果公司的最高层置身事外，还想让其他人照办，最终一定是要失败的，因为人不仅会听其言，更是从观其行中学习的。

# 第4则  理念与文化
一家公司不要试图讨好所有人，实际上自然也是做不到的，有的公司以产品为导向，有的以商业为导向，有的以投资人的利益为导向，总之必须有突出的文化特质，想面面俱到是不可能的。

谷歌是一家以工程师为重心的公司，在初创阶段，佩奇和布林甚至执着于招聘的每一个人都必须是工程师，本书作者CEO施密特和高级副总裁布隆伯格也是工程师出身，招聘的第一个非工程师背影的应该就是给财政部长当过助理的现facebook的运营官。当然随着企业的发展，这个理念慢慢有不再那么坚持，但谷歌仍然是一家以工程师为重的公司，并通过工程师的创造力源源不断的开发出好产品，当然，工程师队伍活力的激发与内部文化特征是分不开的。要能保持这种创新环境，不仅仅是找来工程师这么简单，谷歌在方方面面都有文化氛围保证了这一点。

> 一天佩奇在办公室发现一些搜索广告不尽如人意，他并没有找负责人，也没有开会，而是把搜索结果打印出来贴在公司的公告栏上，下周一，杰夫·迪恩等几位工程师就发出的邮件，详尽地分析了问题出现的原因，提供了一份解决方案，并给出了五人利用周末时间编写出的解决方案模型以及超链接，还附加了测试结果，证明新模型与当时通用的系统相比有哪些优越性。

这个案例，书中是这么分析的：

> 这几位员工并不直接负责广告业务，即便广告业务出了问题也不会归咎到他们头上，但他们竟然贡献出周末时间，不仅解决了别人的问题，还在解决过程中为公司赢利。有了文化氛围的魔力，他们放手解决任何阻碍谷歌成功的严重问题。如果失败了，没有人会以任何方式斥责他们；如果他们成功了，也没有人会对他们的成绩起嫉妒之心。

这个例子，将谷歌企业文化的力量彰显得淋漓尽致。案例虽然非常鼓舞人心，其实也是个水到渠成的事，首先，人才入口把得好，找了对的人，其次谷歌形成了勇于承担责任的骑士文化，到了用兵之时，有骑士敢站出来。所以，像崇祯那样，抱怨没人为国分忧的时候，最该反思的自己，而不是指责大臣。

# 第5则  最后的总结
回到现实天地，也许我们的实际情况与谷歌不同，解决问题不能照搬谷歌的方法。看完本书，给我最大的启示是，人要彻底抛弃妄念，真正从实际出发，从改善内部结构、运行模式开始，才能走得远。有的人，或者团体，放弃思考、不愿改变，却想以当前的面貌获得空前的成功，这就是妄念。总之，想获得空前的成功，必须打造或变成一个新的物种。
